
; Win32 programming headers (WIDE)

include '%include%/macro/stdcall.inc'
include '%include%/macro/cdecl.inc'
include '%include%/macro/import.inc'
include '%include%/macro/export.inc'
include '%include%/macro/resource.inc'
include '%include%/macro/struct.inc'

include '%include%/equatesw/kernel32.inc'
include '%include%/equatesw/user32.inc'
include '%include%/equatesw/gdi32.inc'
include '%include%/equatesw/comctl32.inc'
include '%include%/equatesw/comdlg32.inc'
include '%include%/equatesw/shell32.inc'
