
; Win32 programming headers (ASCII)

include '%include%/macro/stdcall.inc'
include '%include%/macro/cdecl.inc'
include '%include%/macro/import.inc'
include '%include%/macro/export.inc'
include '%include%/macro/resource.inc'
include '%include%/macro/struct.inc'

include '%include%/equatesa/kernel32.inc'
include '%include%/equatesa/user32.inc'
include '%include%/equatesa/gdi32.inc'
include '%include%/equatesa/comctl32.inc'
include '%include%/equatesa/comdlg32.inc'
include '%include%/equatesa/shell32.inc'
